import { StyleSheet } from 'react-native';
import { BottomTabInset, Spacing } from '@/constants/theme';

export const getHomeStyles = (theme: any) => StyleSheet.create({
  container: {
    flex: 1,
  },
  contentContainer: {
    paddingBottom: BottomTabInset + Spacing.four,
  },
  safeArea: {
    flex: 1,
    paddingHorizontal: Spacing.four,
    gap: Spacing.three,
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: Spacing.three,
  },
  welcomeSubtitle: {
    fontSize: 12,
    color: '#81A588',
    fontWeight: 'bold',
    textTransform: 'uppercase',
  },
  welcomeTitle: {
    fontSize: 22,
    fontWeight: '300',
  },
  nameTitle: {
    fontSize: 24,
    fontWeight: 'bold',
  },
  logoutBtn: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    borderWidth: 1,
  },
  logoutText: {
    fontSize: 12,
    fontWeight: '600',
  },
  dashboardSection: {
    gap: Spacing.four,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    marginTop: Spacing.two,
  },
  rowBetween: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  statsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: Spacing.two,
  },
  statCard: {
    flex: 1,
    minWidth: '45%',
    padding: Spacing.three,
    borderRadius: 16,
    gap: Spacing.half,
  },
  statEmoji: {
    fontSize: 24,
  },
  statValue: {
    fontSize: 28,
    fontWeight: 'bold',
  },
  statLabel: {
    fontSize: 12,
    color: '#546E5A',
  },
  primaryActionBtn: {
    height: 52,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: Spacing.two,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  primaryActionBtnText: {
    color: '#FFFFFF',
    fontWeight: 'bold',
    fontSize: 16,
  },
  profileSummaryCard: {
    padding: Spacing.four,
    borderRadius: 18,
    gap: Spacing.three,
  },
  badgeRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  categoryBadge: {
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 20,
  },
  categoryBadgeText: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#2E7D32',
  },
  editProfileSummaryBtn: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#C5DFCC',
  },
  editProfileSummaryBtnText: {
    fontSize: 11,
    fontWeight: 'bold',
    color: '#2E7D32',
  },
  heightText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#546E5A',
  },
  weightDetailsRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    marginVertical: Spacing.one,
  },
  weightCol: {
    alignItems: 'center',
    gap: Spacing.half,
  },
  weightLabel: {
    fontSize: 11,
    color: '#546E5A',
  },
  weightValue: {
    fontSize: 18,
    fontWeight: 'bold',
  },
  weightDivider: {
    width: 1,
    height: 30,
    backgroundColor: '#C5DFCC',
  },
  bmiWrapper: {
    alignItems: 'center',
  },
  bmiCategoryText: {
    fontSize: 10,
    fontWeight: 'bold',
  },
  categoryMetaRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: 'rgba(128, 128, 128, 0.15)',
    padding: 10,
    borderRadius: 10,
  },
  categoryMetaText: {
    fontSize: 12,
  },
  boldText: {
    fontWeight: 'bold',
  },
  dietCard: {
    borderWidth: 2,
    borderRadius: 18,
    overflow: 'hidden',
  },
  dietCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: Spacing.four,
    paddingVertical: Spacing.three,
  },
  dietCardTitle: {
    fontSize: 15,
    fontWeight: 'bold',
  },
  dietCardCal: {
    fontSize: 14,
    fontWeight: '700',
    color: '#2E7D32',
  },
  macrosRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingVertical: 10,
    backgroundColor: 'rgba(46, 125, 50, 0.04)',
    borderBottomWidth: 1,
    borderBottomColor: '#E1EFE4',
  },
  macroCol: {
    alignItems: 'center',
  },
  macroLabel: {
    fontSize: 11,
    color: '#666',
    marginBottom: 2,
  },
  macroValue: {
    fontSize: 13,
    fontWeight: 'bold',
  },
  mealRow: {
    paddingHorizontal: Spacing.four,
    paddingVertical: Spacing.three,
    borderBottomWidth: 1,
    borderBottomColor: '#E1EFE4',
    gap: 4,
  },
  mealLabel: {
    fontSize: 13,
    fontWeight: 'bold',
    color: '#2E7D32',
  },
  mealValue: {
    fontSize: 14,
    lineHeight: 18,
  },
  dietToggleBtn: {
    margin: Spacing.three,
    height: 48,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dietToggleBtnText: {
    color: '#FFFFFF',
    fontWeight: 'bold',
    fontSize: 15,
  },
  noDietCard: {
    padding: Spacing.four,
    borderRadius: 16,
    alignItems: 'center',
  },
  noDietText: {
    fontSize: 14,
    textAlign: 'center',
    color: '#546E5A',
  },
  dietitianCreditsCard: {
    padding: Spacing.four,
    borderRadius: 16,
    gap: Spacing.three,
    marginTop: Spacing.three,
  },
  creditsMainRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.three,
  },
  creditsEmoji: {
    fontSize: 32,
  },
  creditsTextContainer: {
    flex: 1,
  },
  creditsLabel: {
    fontSize: 11,
    color: '#81A588',
    fontWeight: 'bold',
    textTransform: 'uppercase',
  },
  creditsName: {
    fontSize: 16,
    fontWeight: 'bold',
  },
  creditsLocation: {
    fontSize: 13,
    color: '#546E5A',
  },
  creditsPhoto: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#E0E0E0',
  },
  dailyLogCard: {
    padding: Spacing.four,
    borderRadius: 18,
    gap: Spacing.three,
  },
  logSubRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0,0,0,0.05)',
    paddingBottom: Spacing.two,
  },
  logSubRowTitle: {
    fontSize: 14,
    fontWeight: 'bold',
  },
  waterControls: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.three,
  },
  waterBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  waterBtnText: {
    fontSize: 16,
    fontWeight: 'bold',
  },
  waterValueText: {
    fontSize: 14,
    fontWeight: 'bold',
  },
  ratingRow: {
    flexDirection: 'row',
    gap: Spacing.one,
    marginVertical: Spacing.half,
  },
  ratingBtn: {
    width: 28,
    height: 28,
    borderRadius: 6,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: '#C5DFCC',
  },
  ratingText: {
    fontSize: 15,
  },
  symptomsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: Spacing.one,
  },
  symptomChip: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    borderWidth: 1.5,
  },
  symptomChipText: {
    fontSize: 12,
  },
  complianceRow: {
    flexDirection: 'row',
    gap: Spacing.two,
    marginVertical: Spacing.half,
  },
  complianceCard: {
    flex: 1,
    padding: Spacing.two,
    borderRadius: 10,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.05)',
  },
  complianceText: {
    fontSize: 11,
    fontWeight: 'bold',
  },
  saveLogBtn: {
    height: 48,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: Spacing.one,
  },
  saveLogBtnText: {
    color: '#FFFFFF',
    fontWeight: 'bold',
    fontSize: 15,
  },
  appRequestCard: {
    padding: Spacing.three,
    borderRadius: 16,
    gap: Spacing.one,
  },
  appCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  appClientName: {
    fontSize: 15,
    fontWeight: 'bold',
  },
  appDateTime: {
    fontSize: 13,
    color: '#546E5A',
  },
  appNote: {
    fontSize: 12,
    fontStyle: 'italic',
    color: '#546E5A',
    backgroundColor: 'rgba(255,255,255,0.4)',
    padding: 6,
    borderRadius: 6,
    marginTop: 4,
  },
  appActionRow: {
    flexDirection: 'row',
    gap: Spacing.two,
    marginTop: Spacing.two,
  },
  appBtn: {
    flex: 1,
    height: 38,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  appRejectBtn: {
    backgroundColor: '#FFEBEE',
  },
  appRejectText: {
    color: '#C62828',
    fontWeight: 'bold',
    fontSize: 13,
  },
  appApproveText: {
    color: '#FFFFFF',
    fontWeight: 'bold',
    fontSize: 13,
  },
  miniBadge: {
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 8,
  },
  miniBadgeText: {
    fontSize: 10,
    fontWeight: 'bold',
    color: '#2E7D32',
  },
  noItemsCard: {
    padding: Spacing.four,
    borderRadius: 16,
    alignItems: 'center',
  },
  noItemsText: {
    fontSize: 13,
    color: '#546E5A',
  },
  appApprovedCard: {
    padding: Spacing.three,
    borderRadius: 14,
  },
  appApprovedTime: {
    fontSize: 13,
    fontWeight: 'bold',
    color: '#2E7D32',
  },
  smallAppBtn: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
  },
  smallAppBtnText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: 'bold',
  },
  appClientCard: {
    padding: Spacing.three,
    borderRadius: 14,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  appClientText: {
    flex: 1,
  },
  appClientDateTime: {
    fontSize: 14,
    fontWeight: 'bold',
  },
  appClientNote: {
    fontSize: 12,
    color: '#546E5A',
    marginTop: 2,
  },
  statusBadge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  statusBadgeText: {
    fontSize: 11,
    fontWeight: 'bold',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: Spacing.four,
    maxHeight: '85%',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#E1EFE4',
    paddingBottom: Spacing.three,
    marginBottom: Spacing.three,
  },
  modalCloseBtn: {
    padding: 6,
  },
  modalCloseBtnText: {
    fontWeight: 'bold',
    color: '#D32F2F',
  },
  modalForm: {
    gap: Spacing.three,
  },
  inputLabel: {
    fontSize: 13,
    fontWeight: 'bold',
    marginBottom: 4,
  },
  textInput: {
    height: 48,
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 16,
    fontSize: 14,
  },
  textArea: {
    height: 80,
    paddingTop: 12,
    textAlignVertical: 'top',
  },
  saveBtn: {
    height: 52,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: Spacing.four,
  },
  saveBtnText: {
    color: '#FFFFFF',
    fontWeight: 'bold',
    fontSize: 16,
  },
  clientCard: {
    padding: Spacing.four,
    borderRadius: 16,
    marginBottom: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderWidth: 1,
  },
  clientName: {
    fontSize: 16,
    fontWeight: 'bold',
  },
  clientMeta: {
    fontSize: 12,
    marginTop: 2,
  },
  clientActionBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  clientActionText: {
    color: '#FFFFFF',
    fontWeight: 'bold',
  },
  notifCard: {
    padding: Spacing.three,
    borderRadius: 12,
    marginBottom: 8,
  },
  notifTitle: {
    fontSize: 14,
    fontWeight: 'bold',
  },
  notifMessage: {
    fontSize: 12,
    marginVertical: 4,
  },
  notifTime: {
    fontSize: 10,
    alignSelf: 'flex-end',
  },
  notifCloseBtn: {
    padding: 6,
  },
  notifCloseBtnText: {
    fontWeight: 'bold',
    fontSize: 14,
    color: '#2E7D32',
  },
  applicationCard: {
    padding: Spacing.three,
    borderRadius: 14,
    marginBottom: 12,
    gap: 4,
    borderWidth: 1,
  },
  applicationHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  applicantName: {
    fontSize: 15,
    fontWeight: 'bold',
  },
  applicantDetails: {
    fontSize: 12,
  },
  appStatusBadge: {
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 8,
  },
  appStatusBadgeText: {
    fontSize: 10,
    fontWeight: 'bold',
  },
  applicationActionRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 8,
  },
  actionBtn: {
    flex: 1,
    height: 32,
    borderRadius: 6,
    alignItems: 'center',
    justifyContent: 'center',
  },
  actionBtnText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: 'bold',
  },
  notifBellBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  notifBellIcon: {
    fontSize: 18,
  },
  notifBadge: {
    position: 'absolute',
    top: -2,
    right: -2,
    backgroundColor: '#D32F2F',
    width: 16,
    height: 16,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  notifBadgeText: {
    color: '#FFFFFF',
    fontSize: 9,
    fontWeight: 'bold',
  },
  notifHeaderAction: {
    fontSize: 12,
    fontWeight: 'bold',
  },
  analyticsGrid: {
    gap: 16,
  },
  analyticsCard: {
    padding: Spacing.four,
    borderRadius: 18,
    gap: Spacing.two,
  },
  analyticsValue: {
    fontSize: 24,
    fontWeight: 'bold',
  },
  predictionRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0,0,0,0.05)',
    paddingBottom: 8,
  },
  predictionLabel: {
    fontSize: 13,
  },
  predictionValue: {
    fontSize: 14,
    fontWeight: 'bold',
  },
  complianceProgressBg: {
    height: 12,
    borderRadius: 6,
    width: '100%',
    marginTop: 4,
    overflow: 'hidden',
  },
  complianceProgressBar: {
    height: '100%',
    borderRadius: 6,
  },
  predictionDateText: {
    fontSize: 14,
    fontWeight: 'bold',
  },
  predictionDaysText: {
    fontSize: 12,
  },
  correlationRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0,0,0,0.05)',
  },
  correlationFactor: {
    fontSize: 13,
    fontWeight: 'bold',
  },
  correlationCoefficient: {
    fontSize: 14,
    fontWeight: 'bold',
  },
  correlationMeaningBadge: {
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 6,
    marginTop: 4,
    alignSelf: 'flex-start',
  },
  correlationMeaningText: {
    fontSize: 10,
    fontWeight: 'bold',
  },
  secondaryActionBtn: {
    height: 52,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 10,
    backgroundColor: 'transparent',
  },
  secondaryActionBtnText: {
    fontWeight: 'bold',
    fontSize: 15,
  },
  socialRow: {
    flexDirection: 'row',
    gap: 16,
    paddingTop: Spacing.three,
    borderTopWidth: 1,
    borderTopColor: '#E1EFE4',
    justifyContent: 'flex-start',
    alignItems: 'center',
    flexWrap: 'wrap',
  },
  socialIconContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  socialIconBg: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  instagramBg: {
    backgroundColor: '#E1306C',
  },
  linkedinBg: {
    backgroundColor: '#0077B5',
  },
  youtubeBg: {
    backgroundColor: '#FF0000',
  },
  socialIconText: {
    fontSize: 15,
    color: '#FFFFFF',
  },
  socialLabelText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#546E5A',
  },
  noDietitianCard: {
    padding: Spacing.four,
    borderRadius: 18,
    alignItems: 'center',
    gap: Spacing.two,
    marginTop: Spacing.three,
    borderWidth: 1.5,
    borderColor: '#C5DFCC',
    borderStyle: 'dashed',
  },
  noDietitianTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#2E7D32',
  },
  noDietitianDesc: {
    fontSize: 13,
    color: '#546E5A',
    textAlign: 'center',
    lineHeight: 18,
    marginVertical: 4,
  },
  findDietitianCardBtn: {
    paddingVertical: 10,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  findDietitianCardBtnText: {
    fontSize: 14,
  },
  dietitianListCard: {
    padding: Spacing.three,
    borderRadius: 14,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#E1EFE4',
  },
  dietitianListHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 8,
  },
  dietitianListPhoto: {
    width: 44,
    height: 44,
    borderRadius: 22,
  },
  dietitianListName: {
    fontSize: 15,
    fontWeight: 'bold',
    color: '#1C3A24',
  },
  dietitianListNotes: {
    fontSize: 12,
    color: '#546E5A',
  },
  statusBanner: {
    paddingVertical: 6,
    borderRadius: 6,
    alignItems: 'center',
    justifyContent: 'center',
  },
  requestsPanel: {
    padding: Spacing.four,
    borderRadius: 18,
    marginTop: Spacing.three,
    gap: Spacing.two,
  },
  requestsPanelTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#2E7D32',
  },
  requestsPanelSubtitle: {
    fontSize: 12,
    color: '#666666',
  },
  requestCard: {
    width: 180,
    padding: 12,
    borderRadius: 12,
    gap: 4,
    borderWidth: 1,
    borderColor: '#C5DFCC',
  },
  requestClientName: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#1C3A24',
  },
  requestClientMeta: {
    fontSize: 11,
    color: '#546E5A',
  },
  requestClientCategory: {
    fontSize: 11,
    color: '#2E7D32',
    fontWeight: 'bold',
  },
  requestActionRow: {
    flexDirection: 'row',
    gap: 6,
    marginTop: 8,
  },
  requestBtn: {
    flex: 1,
    height: 28,
    borderRadius: 6,
    alignItems: 'center',
    justifyContent: 'center',
  },
  approveRequestBtn: {
    backgroundColor: '#2E7D32',
  },
  rejectRequestBtn: {
    backgroundColor: '#D32F2F',
  },
  requestBtnText: {
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: 'bold',
  },
  chatMsgRow: {
    flexDirection: 'row',
    width: '100%',
    marginVertical: 4,
  },
  chatBubble: {
    maxWidth: '75%',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 16,
    gap: 4,
  },
  myBubble: {
    borderBottomRightRadius: 2,
  },
  otherBubble: {
    borderBottomLeftRadius: 2,
  },
  chatText: {
    fontSize: 14,
    lineHeight: 20,
  },
  chatTime: {
    fontSize: 10,
    alignSelf: 'flex-end',
  },
  chatInputRow: {
    flexDirection: 'row',
    padding: 12,
    borderTopWidth: 1,
    alignItems: 'center',
    gap: Spacing.two,
  },
  chatInput: {
    flex: 1,
    height: 40,
    borderRadius: 20,
    borderWidth: 1,
    paddingHorizontal: 16,
    fontSize: 14,
  },
  chatSendBtn: {
    width: 70,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  chatSendBtnText: {
    color: '#FFFFFF',
    fontWeight: 'bold',
    fontSize: 13,
  },
  broadcastBubble: {
    backgroundColor: '#FFF3E0',
    borderColor: '#FFE0B2',
    borderWidth: 1,
    borderBottomLeftRadius: 2,
    width: '90%',
    maxWidth: '90%',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 16,
    gap: 4,
  },
  broadcastTitle: {
    fontSize: 13,
    fontWeight: 'bold',
    color: '#E65100',
  },
  broadcastContent: {
    fontSize: 14,
    color: '#4E342E',
    lineHeight: 20,
  },
  broadcastFooter: {
    fontSize: 10,
    color: '#E65100',
    fontStyle: 'italic',
    marginTop: 4,
  },
});
